name: Hash Chain

on:
  push:
  workflow_dispatch:

jobs:
  hash-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Compute hash 42451913
        run: |
          echo -n "${{ secrets.MY_SECRET }}github-verified" | sha256sum | cut -c1-10 > verify.txt

      - name: Upload artifact 42451913
        uses: actions/upload-artifact@v3
        with:
          name: verify-hash-42451913
          path: verify.txt
